language: java
cache:
  directories:
  - $HOME/.m2
jdk:
- oraclejdk8
notifications:
  email: false
sudo: required
services:
- docker
script:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- docker push fabianpoels/destination-service:0.0.1
